[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-XSS-Protection = "1; mode=block"

[[headers]]
  for = "/data/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200
